const express = require("express")
const app = express()
require("dotenv").config()
require("../../database/connection")
app.use(express.json())
app.use(express.urlencoded({extended:true}))
const userRoutes =  require("../../routes/user.routes")
app.use("/user",userRoutes)
const imgRoutes =  require("../../routes/image.routes")
app.use("/user",imgRoutes)
app.get("*", (req,res)=> res.send( {error:"Invalid URL"} ) )
module.exports=app