const express = require("express")
const app = express()
require("dotenv").config()
require("../../database/connection")
app.use(express.json())
app.use(express.urlencoded({extended:true}))
const cors = require("cors")
app.use(cors())
const userRoutes =  require("../../routes/user.routes")
app.use("/user",userRoutes)
const productRoutes =  require("../../routes/product.routes")
app.use("/product",productRoutes)
const orderRoutes =  require("../../routes/order.routes")
app.use("/order",orderRoutes)
const cartRoutes =  require("../../routes/cart.routes")
app.use("/cart",cartRoutes)
const categoryRoutes =  require("../../routes/category.routes")
app.use("/category",categoryRoutes)
app.get("*", (req,res)=> res.send( {error:"Invalid URL"} ) )
module.exports=app